FROM eclipse-temurin:21@sha256:30cda4693fbb923f2145a0a4e23d03e75b0477df5daccd12049e372e4337aa59
COPY ./ /location-service
WORKDIR /location-service
RUN chmod +x ./gradlew
RUN ./gradlew
CMD ["./gradlew", "run"]
