services:
  cassandra-db:
    image: cassandra:latest@sha256:2d241468ad9d0c091905dddb8d4e5cf4bdfbbfbd6d2acdbd4c7c312e43da93e1
    container_name: cassandra-db
    ports:
      - "9042:9042"
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 5s
      timeout: 5s
      retries: 60

  cassandra-init:
    image: cassandra:latest@sha256:2d241468ad9d0c091905dddb8d4e5cf4bdfbbfbd6d2acdbd4c7c312e43da93e1
    depends_on:
      cassandra-db:
        condition: service_healthy
    volumes:
      - ./tracking-actors/src/main/resources/db-scripts/create-tables.cql:/create-actor-tables.cql
      - ./storage/src/main/resources/db-scripts/create-tables.cql:/create-storage-tables.cql
    command:
      /bin/sh -c "cqlsh cassandra-db -f /create-actor-tables.cql && cqlsh cassandra-db -f /create-storage-tables.cql"

  rabbitmq-broker:
    image: rabbitmq:4-management@sha256:0a5949780b51b3cd4ded8ba214bad69ca27f1717e7496e350618ccf828895603
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"   # the port RabbitMQ will listen on
      - "15672:15672" # the port the dashboard web service will be available from
