FROM eclipse-temurin:21@sha256:5ad4efff3364b06c61578b267138359bcba92acc20dfd533f35b75c709a6f10b
COPY ./ /location-service
WORKDIR /location-service
RUN chmod +x ./gradlew
RUN ./gradlew
CMD ["./gradlew", "run"]
