services:
  cassandra-db:
    image: cassandra:latest@sha256:93f9a71ef04e370f754c78c78871648dfce8023958a455298d6a689caa607182
    container_name: cassandra-db
    ports:
      - "9042:9042"
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 5s
      timeout: 5s
      retries: 60

  cassandra-init:
    image: cassandra:latest@sha256:93f9a71ef04e370f754c78c78871648dfce8023958a455298d6a689caa607182
    depends_on:
      cassandra-db:
        condition: service_healthy
    volumes:
      - ./tracking-actors/src/main/resources/db-scripts/create-tables.cql:/create-actor-tables.cql
      - ./storage/src/main/resources/db-scripts/create-tables.cql:/create-storage-tables.cql
    command:
      /bin/sh -c "cqlsh cassandra-db -f /create-actor-tables.cql && cqlsh cassandra-db -f /create-storage-tables.cql"

  rabbitmq-broker:
    image: rabbitmq:4-management@sha256:d0e1a5a232c5b0f8cfaf5d940a3b9d9c12930ffb667230e79815bc3013112835
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"   # the port RabbitMQ will listen on
      - "15672:15672" # the port the dashboard web service will be available from
