services:
  cassandra-db:
    image: cassandra:latest@sha256:26dbef3c7b66bda0587d99c387c7d4f57cbb1f76acbc87db324a62f6372b3fdf
    container_name: cassandra-db
    ports:
      - "9042:9042"
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 5s
      timeout: 5s
      retries: 60

  cassandra-init:
    image: cassandra:latest@sha256:26dbef3c7b66bda0587d99c387c7d4f57cbb1f76acbc87db324a62f6372b3fdf
    depends_on:
      cassandra-db:
        condition: service_healthy
    volumes:
      - ./tracking-actors/src/main/resources/db-scripts/create-tables.cql:/create-actor-tables.cql
      - ./storage/src/main/resources/db-scripts/create-tables.cql:/create-storage-tables.cql
    command:
      /bin/sh -c "cqlsh cassandra-db -f /create-actor-tables.cql && cqlsh cassandra-db -f /create-storage-tables.cql"

  rabbitmq-broker:
    image: rabbitmq:4-management@sha256:fda93651be25626234e47122aa12f74ba0510cd1e3d32b5d5438083bb9081833
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"   # the port RabbitMQ will listen on
      - "15672:15672" # the port the dashboard web service will be available from
