services:
  cassandra-db:
    image: cassandra:latest@sha256:ee89b3d7abbdf8efe8d7d3e3e2654d7b4a293bd24fdf6ba1debc36af5e9c9ec7
    container_name: cassandra-db
    ports:
      - "9042:9042"
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 5s
      timeout: 5s
      retries: 60

  cassandra-init:
    image: cassandra:latest@sha256:ee89b3d7abbdf8efe8d7d3e3e2654d7b4a293bd24fdf6ba1debc36af5e9c9ec7
    depends_on:
      cassandra-db:
        condition: service_healthy
    volumes:
      - ./tracking-actors/src/main/resources/db-scripts/create-tables.cql:/create-actor-tables.cql
      - ./storage/src/main/resources/db-scripts/create-tables.cql:/create-storage-tables.cql
    command:
      /bin/sh -c "cqlsh cassandra-db -f /create-actor-tables.cql && cqlsh cassandra-db -f /create-storage-tables.cql"

  rabbitmq-broker:
    image: rabbitmq:4-management@sha256:826db87b2d2d8c18748768d04b9322b6a26d76c9d22b8068ca34fd42c37b4e0e
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"   # the port RabbitMQ will listen on
      - "15672:15672" # the port the dashboard web service will be available from
